model:
  encoder:
    architecture: "inverted_residual_single_category_v2"
    input_dims: [480, 320]
    n_context: 0
    only_train_encoder: False
    use_batch_norm: False
  classifier:
    architecture: "classifier_ires_single_category_v3"
    patch_size: [32, 32]
    n_meta: 0
    with_offsets: True
    use_batch_norm: False

training:
  epochs: 80
  initial_epoch: 0
  batch_size: 32
  verbose: 1
  from_checkpoint: False # < when starting training from checkpoint
  from_model: False # < when loading an existing model
  load_checkpoint:
    initial_epoch: 39
    timestamp: "20251027-123055" 
    encoder_only: False # < when only loading the encoder
    verbose: True
  load_model:
    timestamp: "20251027-123055"
    filepath: "models/finished/"
    encoder_only: True # < when only loading the encoder
    verbose: True

categories:
  ball:
    object_size: 0.175
    object_height: 0.05
    n_classes: 1
    n_candidates: 5
  # penaltyMark:
  #   object_size: 0.175
  #   object_height: 0.0
  #   n_classes: 1
  #   n_candidates: 5
  # field:
  #   object_size: 0.2
  #   n_classes: 1 # penalty mark, center mark, X intersection, L intersection, T intersection, goal post
  #   n_candidates: 7
  # player:
  #   object_size: 0.5
  #   n_classes: 1
  intersections:
    object_size: 0.175
    object_height: 0.0
    n_classes: 4 # types + background class
    n_candidates: 10

callbacks:
  reduce_lr:
    monitor: "val_total_loss"
    mode: "min"
    factor: 0.5
    patience: 16
    min_lr: 0.000001
  early_stopping:
    monitor: "val_total_loss"
    mode: "min"
    patience: 40
  log_dir: "logs/fit/"
  checkpoint_dir: "models/checkpoints/"

data:
  train_path: "data/tfrecords/train_ds_v2*.tfrecords"
  val_path: "data/tfrecords/val_ds_v2*.tfrecords"